version: "3"

services:
  web1:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: music_service1
    volumes:
      - .:/music_service
    ports:
      - "8000:8000"

  web2:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8001"
    container_name: music_service2
    volumes:
      - .:/music_service
    ports:
      - "8001:8001"
