version: "3"

services:
  web1:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && DJANGO_RUNSERVER_PORT=8000 python manage.py runserver 0.0.0.0:8001"
    container_name: music_service1
    volumes:
      - .:/music_service
    ports:
      - "8001:8001"
    depends_on:
      - redis

  web2:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && DJANGO_RUNSERVER_PORT=8001 python manage.py runserver 0.0.0.0:8002"
    container_name: music_service2
    volumes:
      - .:/music_service
    ports:
      - "8002:8002"
    depends_on:
      - redis

  celery1:
    build: .
    command: celery -A OnlineShop worker --loglevel=info --concurrency=2
    container_name: celery_worker1
    volumes:
      - .:/music_service
    depends_on:
      - web1
      - redis # Додаємо залежність від Redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  celery2:
    build: .
    command: celery -A OnlineShop worker --loglevel=info --concurrency=2
    container_name: celery_worker2
    volumes:
      - .:/music_service
    depends_on:
      - web2
      - redis # Додаємо залежність від Redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: "redis:latest"
    container_name: redis_server
    ports:
      - "6379:6379"
