# Generated by Django 2.2.8 on 2023-11-16 22:04

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_good_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPRESSING', 'COMPRESSING'), ('COMPRESSED', 'COMPRESSED')], default=goods.models.ImageStatus('PENDING'), max_length=2),
        ),
        migrations.AddField(
            model_name='goodimage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPRESSING', 'COMPRESSING'), ('COMPRESSED', 'COMPRESSED')], default=goods.models.ImageStatus('PENDING'), max_length=2),
        ),
    ]
