# Generated by Django 2.2.8 on 2023-11-26 12:43

from django.db import migrations, models
import goods.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20231116_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPRESSING', 'COMPRESSING'), ('COMPRESSED', 'COMPRESSED')], default=goods.models.ImageStatus('PENDING'), max_length=10),
        ),
        migrations.AlterField(
            model_name='goodimage',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('COMPRESSING', 'COMPRESSING'), ('COMPRESSED', 'COMPRESSED')], default=goods.models.ImageStatus('PENDING'), max_length=10),
        ),
    ]
